# Generated by Django 5.1.3 on 2024-11-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=5),
        ),
    ]
