# Generated by Django 5.1.3 on 2024-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0002_article_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images/% Y/% m/% d/'),
        ),
    ]
