# Generated by Django 5.1.3 on 2024-11-17 09:13

import uuid
import yoticles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=yoticles.models.get_image_url),
        ),
    ]
