# Generated by Django 5.1.3 on 2024-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0004_alter_article_id_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
