# Generated by Django 5.1.3 on 2024-11-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0005_user_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_date',
        ),
    ]
