# Generated by Django 5.0.6 on 2024-11-19 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0006_remove_user_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
