# Generated by Django 5.0.6 on 2024-11-20 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
