# Generated by Django 5.0.6 on 2024-11-21 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoticles', '0009_article_saves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='saves',
        ),
        migrations.AddField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
